# Generated by Django 4.2.7 on 2025-01-23 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import kakemono.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kakemono",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Titre"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="kakemonos/", verbose_name="Image"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, verbose_name="Disponible"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kakémono",
                "verbose_name_plural": "Kakémonos",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="KakemonoReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        validators=[kakemono.models.validate_future_date],
                        verbose_name="Date de début",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        validators=[kakemono.models.validate_future_date],
                        verbose_name="Date de fin",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("confirmed", "Confirmée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "kakemonos",
                    models.ManyToManyField(
                        related_name="reservations",
                        to="kakemono.kakemono",
                        verbose_name="Kakémonos",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kakemono_reservations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réservation de kakémono",
                "verbose_name_plural": "Réservations de kakémonos",
                "ordering": ["-created_at"],
            },
        ),
    ]
