# Generated by Django 4.2.7 on 2025-01-29 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("kakemono", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kakemonoreservation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kakemono_reservations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="kakemonoreservation",
            name="first_name",
            field=models.CharField(
                default="", max_length=100, verbose_name="Prénom"
            ),
        ),
        migrations.AddField(
            model_name="kakemonoreservation",
            name="last_name",
            field=models.CharField(
                default="", max_length=100, verbose_name="Nom"
            ),
        ),
        migrations.AlterField(
            model_name="kakemonoreservation",
            name="notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Notes (optionnel)"
            ),
        ),
    ]
