# Generated by Django 4.2.7 on 2025-01-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kakemono", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kakemonoreservation",
            name="first_name",
            field=models.CharField(
                default="", max_length=100, verbose_name="Prénom"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kakemonoreservation",
            name="last_name",
            field=models.CharField(
                default="", max_length=100, verbose_name="Nom"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="kakemonoreservation",
            name="notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Notes (optionnel)"
            ),
        ),
    ]
