# Generated by Django 4.2.2 on 2026-05-21 06:59

from django.db import migrations, models
import kakemono.models


class Migration(migrations.Migration):

    dependencies = [
        ('kakemono', '0003_alter_kakemonoreservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kakemono',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='kakemonoreservation',
            name='end_date',
            field=models.DateField(db_index=True, validators=[kakemono.models.validate_future_date], verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='kakemonoreservation',
            name='start_date',
            field=models.DateField(db_index=True, validators=[kakemono.models.validate_future_date], verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='kakemonoreservation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée')], db_index=True, default='pending', max_length=20, verbose_name='Statut'),
        ),
    ]
