# Generated by Django 4.2.2 on 2026-05-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakemono', '0004_alter_kakemono_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kakemono',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='kakemonoreservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
    ]
