# Generated by Django 4.2.2 on 2026-06-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kakemono", "0006_alter_kakemono_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kakemonoreservation",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="Prénom"),
        ),
        migrations.AlterField(
            model_name="kakemonoreservation",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="Nom"),
        ),
    ]
