# Generated by Django 5.1.7 on 2025-09-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("distribution", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campagnedistribution",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("active", "En cours"),
                    ("completed", "Terminée"),
                    ("cancelled", "Annulée"),
                ],
                default="active",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
