# Generated by Django 4.2.2 on 2026-05-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_alter_campagnedistribution_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagnedistribution',
            name='end_date',
            field=models.DateField(db_index=True, help_text='Date de fin prévue de la campagne', verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='campagnedistribution',
            name='start_date',
            field=models.DateField(db_index=True, help_text='Date de début de la campagne', verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='campagnedistribution',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('active', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], db_index=True, default='active', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='is_distributed',
            field=models.BooleanField(db_index=True, default=False, help_text='Cochez si le flyer a été distribué dans ce lieu', verbose_name='Distribué'),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Décochez pour désactiver ce lieu', verbose_name='Actif'),
        ),
    ]
