# Generated by Django 4.2.30 on 2026-09-11 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0004_alter_campagnedistribution_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='quantite',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Nombre de flyers/documents à distribuer dans ce lieu', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité'),
        ),
    ]
