# Generated by Django 4.2.30 on 2026-09-11 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distribution', '0005_distribution_quantite'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampagneLieuExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluded_at', models.DateTimeField(auto_now_add=True, verbose_name='Date du retrait')),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lieux_exclus', to='distribution.campagnedistribution', verbose_name='Campagne')),
                ('excluded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lieux_exclus', to=settings.AUTH_USER_MODEL, verbose_name='Retiré par')),
                ('lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions_campagne', to='distribution.lieu', verbose_name='Lieu')),
            ],
            options={
                'verbose_name': "Lieu retiré d'une campagne",
                'verbose_name_plural': 'Lieux retirés des campagnes',
                'ordering': ['campagne', 'lieu__commune__name', 'lieu__name'],
                'unique_together': {('campagne', 'lieu')},
            },
        ),
    ]
