"""Migration initiale pour créer le modèle PageVisit."""

# Generated by Django 4.2.7 on 2024-12-18 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration initiale pour l'application Analytics.

    Cette migration crée la table de base pour le suivi des visites de pages.
    """

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PageVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=2000)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.CharField(max_length=1000)),
                (
                    "referrer",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"],
                        name="analytics_p_timesta_8f24f0_idx",
                    ),
                    models.Index(
                        fields=["url"], name="analytics_p_url_71fff6_idx"
                    ),
                    models.Index(
                        fields=["user"], name="analytics_p_user_id_91fb05_idx"
                    ),
                ],
            },
        ),
    ]
