"""Migration pour ajouter des champs au modèle PageVisit."""

# Generated by Django 4.2.7 on 2024-12-18 08:31

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    """Ajout de champs pour le suivi avancé des visites.

    Cette migration ajoute les champs device_type, is_bounce et time_spent
    au modèle PageVisit.
    """

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagevisit",
            name="device_type",
            field=models.CharField(
                choices=[
                    ("desktop", "Desktop"),
                    ("mobile", "Mobile"),
                    ("tablet", "Tablet"),
                ],
                default="desktop",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pagevisit",
            name="is_bounce",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pagevisit",
            name="session_id",
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
        migrations.AddField(
            model_name="pagevisit",
            name="time_spent",
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="pagevisit",
            index=models.Index(
                fields=["device_type"], name="analytics_p_device__60c617_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pagevisit",
            index=models.Index(
                fields=["session_id"], name="analytics_p_session_9a744f_idx"
            ),
        ),
    ]
