# Generated by Django 4.2.2 on 2026-05-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_pagevisit_device_type_pagevisit_is_bounce_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagevisit',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='is_bounce',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
