# Generated by Django 4.2.2 on 2026-05-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_pagevisit_ip_address_alter_pagevisit_is_bounce'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pagevisit',
            index=models.Index(fields=['ip_address', 'url', '-timestamp'], name='analytics_p_ip_addr_e8a442_idx'),
        ),
    ]
