# Generated by Django 4.2.2 on 2026-05-21 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0004_pagevisit_analytics_p_ip_addr_e8a442_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagevisit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_visits', to=settings.AUTH_USER_MODEL),
        ),
    ]
