# Generated by Django 4.2.30 on 2026-08-26 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="newsletter/blocks/", verbose_name="Image"
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Texte alternatif"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ajoutée le"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Téléversée par",
                    ),
                ),
            ],
            options={
                "verbose_name": "image newsletter",
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Titre interne"),
                ),
                (
                    "subject",
                    models.CharField(
                        default="Newsletter Médi@'pass",
                        max_length=200,
                        verbose_name="Objet de l'email",
                    ),
                ),
                (
                    "preheader",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Texte d'aperçu"
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Début de la période")),
                ("period_end", models.DateField(verbose_name="Fin de la période")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Brouillon"), ("sent", "Terminée")],
                        db_index=True,
                        default="draft",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#4a6fa5",
                        max_length=7,
                        verbose_name="Couleur principale",
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#f4f6fb", max_length=7, verbose_name="Couleur de fond"
                    ),
                ),
                (
                    "font_family",
                    models.CharField(
                        choices=[
                            ("Arial, Helvetica, sans-serif", "Arial"),
                            (
                                "'Helvetica Neue', Helvetica, Arial, sans-serif",
                                "Helvetica",
                            ),
                            ("Verdana, Geneva, sans-serif", "Verdana"),
                            ("Tahoma, Verdana, Geneva, sans-serif", "Tahoma"),
                            ("'Trebuchet MS', Helvetica, sans-serif", "Trebuchet MS"),
                            ("Georgia, 'Times New Roman', serif", "Georgia"),
                            ("'Times New Roman', Times, serif", "Times New Roman"),
                        ],
                        default="Arial, Helvetica, sans-serif",
                        max_length=100,
                        verbose_name="Police",
                    ),
                ),
                (
                    "sender_campaign_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=50,
                        verbose_name="ID campagne Sender.net",
                    ),
                ),
                (
                    "sender_pushed_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Poussée vers Sender.net",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créée le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifiée le"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="newsletters",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créée par",
                    ),
                ),
            ],
            options={
                "verbose_name": "newsletter",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LibraryProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="Nom de la médiathèque"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="newsletter/libraries/",
                        verbose_name="Image / logo",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Téléphone"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Adresse"
                    ),
                ),
                (
                    "opening_hours",
                    models.TextField(
                        blank=True,
                        help_text="Une ligne par jour, ex. « Lundi : 14h - 18h »",
                        verbose_name="Horaires d'ouverture",
                    ),
                ),
                (
                    "closures",
                    models.TextField(
                        blank=True,
                        help_text="Une fermeture par ligne",
                        verbose_name="Fermetures exceptionnelles",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modification"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="library_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Compte médiathèque",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiche médiathèque",
            },
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(db_index=True, verbose_name="Position"),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("heading", "Titre"),
                            ("text", "Texte"),
                            ("image", "Image"),
                            ("button", "Bouton"),
                            ("separator", "Séparateur"),
                            ("spacer", "Espaceur"),
                            ("workshop", "Atelier"),
                            ("event", "Événement"),
                            ("library", "Médiathèque"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "content",
                    models.JSONField(blank=True, default=dict, verbose_name="Contenu"),
                ),
                (
                    "style",
                    models.JSONField(blank=True, default=dict, verbose_name="Style"),
                ),
                (
                    "newsletter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="newsletter.newsletter",
                    ),
                ),
            ],
            options={
                "verbose_name": "bloc",
                "ordering": ["position"],
            },
        ),
        migrations.AddConstraint(
            model_name="block",
            constraint=models.UniqueConstraint(
                fields=("newsletter", "position"),
                name="unique_block_position_per_newsletter",
            ),
        ),
    ]
