# Generated by Django 4.2.30 on 2026-08-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="workshop_default_variant",
            field=models.CharField(
                choices=[("card", "Carte empilée"), ("side", "Image à gauche")],
                default="card",
                max_length=10,
                verbose_name="Mise en page par défaut des ateliers",
            ),
        ),
    ]
