# Generated by Django 4.2.30 on 2026-08-26 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_workshop_variant_global"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(db_index=True, verbose_name="Position"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Titre de section"
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#ffffff", max_length=7, verbose_name="Couleur de fond"
                    ),
                ),
            ],
            options={
                "verbose_name": "section",
                "ordering": ["position"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="block",
            name="unique_block_position_per_newsletter",
        ),
        migrations.AddField(
            model_name="libraryprofile",
            name="facebook_url",
            field=models.URLField(blank=True, max_length=255, verbose_name="Facebook"),
        ),
        migrations.AddField(
            model_name="libraryprofile",
            name="instagram_url",
            field=models.URLField(blank=True, max_length=255, verbose_name="Instagram"),
        ),
        migrations.AddField(
            model_name="libraryprofile",
            name="website",
            field=models.URLField(blank=True, max_length=255, verbose_name="Site web"),
        ),
        migrations.AddField(
            model_name="section",
            name="library_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sections",
                to="newsletter.libraryprofile",
                verbose_name="Médiathèque",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="newsletter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="newsletter.newsletter",
            ),
        ),
        migrations.AddField(
            model_name="block",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocks",
                to="newsletter.section",
                verbose_name="Section",
            ),
        ),
        migrations.AddConstraint(
            model_name="block",
            constraint=models.UniqueConstraint(
                fields=("newsletter", "section", "position"),
                name="unique_block_position_per_section",
            ),
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.UniqueConstraint(
                fields=("newsletter", "position"),
                name="unique_section_position_per_newsletter",
            ),
        ),
    ]
