# Generated by Django 4.2.30 on 2026-08-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0003_sections_and_socials"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="workshop_bg_color",
            field=models.CharField(
                blank=True,
                default="#ffffff",
                help_text="Vide = transparent (fond de section visible)",
                max_length=7,
                verbose_name="Fond par défaut des cartes atelier",
            ),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="workshop_border_color",
            field=models.CharField(
                default="#e3e9f4", max_length=7, verbose_name="Couleur bordure"
            ),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="workshop_border_radius",
            field=models.CharField(
                choices=[
                    ("0", "Carré (0)"),
                    ("6", "Petit 6px"),
                    ("8", "Moyen 8px"),
                    ("12", "Grand 12px"),
                    ("16", "Très grand 16px"),
                    ("9999", "Pill"),
                ],
                default="12",
                max_length=4,
                verbose_name="Rayon par défaut",
            ),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="workshop_border_style",
            field=models.CharField(
                choices=[
                    ("none", "Aucune"),
                    ("solid", "Pleine"),
                    ("dashed", "Pointillée"),
                    ("left-accent", "Accent à gauche"),
                ],
                default="solid",
                max_length=12,
                verbose_name="Bordure par défaut",
            ),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="workshop_border_width",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Épaisseur bordure (px)"
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="border_color",
            field=models.CharField(
                blank=True, default="", max_length=7, verbose_name="Couleur bordure"
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="border_radius",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "Carré (0)"),
                    ("6", "Petit 6px"),
                    ("8", "Moyen 8px"),
                    ("12", "Grand 12px"),
                    ("16", "Très grand 16px"),
                    ("9999", "Pill"),
                ],
                default="",
                help_text="Vide = hérite du global",
                max_length=4,
                verbose_name="Rayon",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="border_style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "Aucune"),
                    ("solid", "Pleine"),
                    ("dashed", "Pointillée"),
                    ("left-accent", "Accent à gauche"),
                ],
                default="",
                help_text="Vide = hérite du global",
                max_length=12,
                verbose_name="Bordure",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="border_width",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Épaisseur bordure (px)"
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="workshop_default_variant",
            field=models.CharField(
                choices=[
                    ("card", "Carte empilée"),
                    ("side", "Image à gauche"),
                    ("side-left", "Image à gauche"),
                    ("side-right", "Image à droite"),
                    ("compact", "Compact (liste)"),
                    ("timeline", "Timeline"),
                ],
                default="card",
                max_length=12,
                verbose_name="Mise en page par défaut des ateliers",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="background_color",
            field=models.CharField(
                blank=True,
                default="#ffffff",
                help_text="Vide = transparent",
                max_length=7,
                verbose_name="Couleur de fond",
            ),
        ),
    ]
