# Generated by Django 4.2.30 on 2026-08-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0004_workshop_variants_and_borders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="workshop_bg_color",
            field=models.CharField(
                blank=True,
                default="#ffffff",
                help_text="Vide ou 'transparent' = fond de section visible",
                max_length=20,
                verbose_name="Fond par défaut des cartes atelier",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="workshop_border_color",
            field=models.CharField(
                blank=True,
                default="#e3e9f4",
                max_length=20,
                verbose_name="Couleur bordure",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="background_color",
            field=models.CharField(
                blank=True,
                default="#ffffff",
                help_text="Vide ou 'transparent' = fond de newsletter visible",
                max_length=20,
                verbose_name="Couleur de fond",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="border_color",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Couleur bordure"
            ),
        ),
    ]
