# Generated by Django 4.2.30 on 2026-08-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0005_transparent_and_border_tweaks"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="workshop_text_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Vide = couleur par défaut de la variante",
                max_length=20,
                verbose_name="Couleur texte ateliers",
            ),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="workshop_title_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Vide = couleur par défaut de la variante",
                max_length=20,
                verbose_name="Couleur titres ateliers",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="text_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Vide = hérite du global",
                max_length=20,
                verbose_name="Couleur du texte",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="title_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Vide = hérite du global",
                max_length=20,
                verbose_name="Couleur des titres",
            ),
        ),
    ]
