# Generated by Django 4.2.30 on 2026-08-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0006_section_title_text_colors"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="content_text_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Texte des blocs à l'intérieur",
                max_length=20,
                verbose_name="Couleur texte du contenu",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="content_title_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Titres des ateliers/blocs à l'intérieur",
                max_length=20,
                verbose_name="Couleur titres du contenu",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="text_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Texte de l'en-tête",
                max_length=20,
                verbose_name="Couleur texte section",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="title_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Titre de l'en-tête",
                max_length=20,
                verbose_name="Couleur titre section",
            ),
        ),
    ]
