# Generated by Django 4.2.30 on 2026-08-27 12:35

from django.db import migrations, models


def _populate_cached_workshop_id(apps, schema_editor):
    Block = apps.get_model("newsletter", "Block")
    for b in Block.objects.filter(cached_workshop_id__isnull=True).iterator(chunk_size=1000):
        wid = (b.content or {}).get("workshop_id")
        if wid is not None:
            try:
                wid_int = int(wid)
            except (TypeError, ValueError):
                continue
            Block.objects.filter(pk=b.pk).update(cached_workshop_id=wid_int)


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0007_section_content_colors"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="cached_workshop_id",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Atelier source (cache)",
            ),
        ),
        migrations.AddIndex(
            model_name="block",
            index=models.Index(
                fields=["newsletter", "block_type", "cached_workshop_id"],
                name="idx_block_nl_type_ws",
            ),
        ),
        migrations.RunPython(
            _populate_cached_workshop_id, reverse_code=migrations.RunPython.noop
        ),
    ]
