# Generated by Django 4.2.30 on 2026-08-28 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("newsletter", "0008_audit_fixes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libraryprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newsletter_library_profile_old",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Compte médiathèque",
            ),
        ),
    ]
