# Generated by Django 4.2.30 on 2026-08-28 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_mediatheque_profile"),
        ("newsletter", "0009_fix_related_name_temp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="library_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sections",
                to="accounts.libraryprofile",
                verbose_name="Médiathèque",
            ),
        ),
        migrations.DeleteModel(
            name="LibraryProfile",
        ),
    ]
