# Generated by Django 4.2.30 on 2026-08-28 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("newsletter", "0010_move_profile_to_accounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="header_align",
            field=models.CharField(
                choices=[("left", "Gauche"), ("center", "Centré"), ("right", "Droite")],
                default="left",
                max_length=10,
                verbose_name="Alignement du texte de l'en-tête",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="header_height",
            field=models.CharField(
                choices=[
                    ("compact", "Compact — 120px"),
                    ("default", "Standard — 180px"),
                    ("large", "Grand — 260px"),
                ],
                default="default",
                help_text="Grandeur du bloc médiathèque (rendu email optimisé)",
                max_length=10,
                verbose_name="Hauteur de l'en-tête",
            ),
        ),
        migrations.CreateModel(
            name="HeaderPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="Nom du preset"
                    ),
                ),
                (
                    "header_height",
                    models.CharField(
                        choices=[
                            ("compact", "Compact — 120px"),
                            ("default", "Standard — 180px"),
                            ("large", "Grand — 260px"),
                        ],
                        default="default",
                        max_length=10,
                        verbose_name="Hauteur de l'en-tête",
                    ),
                ),
                (
                    "header_align",
                    models.CharField(
                        choices=[
                            ("left", "Gauche"),
                            ("center", "Centré"),
                            ("right", "Droite"),
                        ],
                        default="left",
                        max_length=10,
                        verbose_name="Alignement du texte",
                    ),
                ),
                (
                    "title_color",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Vide = blanc (sur bannière)",
                        max_length=20,
                        verbose_name="Couleur du titre",
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Vide = blanc (sur bannière)",
                        max_length=20,
                        verbose_name="Couleur du texte",
                    ),
                ),
                (
                    "overlay_strength",
                    models.CharField(
                        default="0.35",
                        help_text="0.10 à 0.70 — assombrit la bannière pour lire le texte",
                        max_length=20,
                        verbose_name="Intensité du voile",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "preset d'en-tête",
                "verbose_name_plural": "presets d'en-tête",
                "ordering": ["name"],
            },
        ),
    ]
