# Generated by Django 4.2.30 on 2026-08-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0011_add_section_header_height_and_presets"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="header_overlay",
            field=models.CharField(
                blank=True,
                default="0.35",
                help_text="0.10 à 0.70 — assombrit la bannière pour lire le texte",
                max_length=20,
                verbose_name="Intensité du voile sur la bannière",
            ),
        ),
    ]
