# Generated by Django 4.2.30 on 2026-08-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0013_seed_header_presets"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="show_header_address",
            field=models.BooleanField(
                default=True, verbose_name="Afficher l'adresse dans l'en-tête"
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="show_header_phone",
            field=models.BooleanField(
                default=True, verbose_name="Afficher le téléphone dans l'en-tête"
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="show_header_socials",
            field=models.BooleanField(
                default=True,
                help_text="Site web, Facebook, Instagram, YouTube, TikTok, X — selon les liens renseignés dans la fiche.",
                verbose_name="Afficher les boutons réseaux sociaux dans l'en-tête",
            ),
        ),
    ]
