# Generated by Django 4.2.30 on 2026-08-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0014_add_section_show_header_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="show_header_socials",
        ),
        migrations.AddField(
            model_name="section",
            name="show_header_badge",
            field=models.BooleanField(
                default=True, verbose_name="Afficher le badge « Médiathèque »"
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="show_header_facebook",
            field=models.BooleanField(
                default=True, verbose_name="Afficher le bouton Facebook"
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="show_header_instagram",
            field=models.BooleanField(
                default=True, verbose_name="Afficher le bouton Instagram"
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="show_header_tiktok",
            field=models.BooleanField(
                default=True, verbose_name="Afficher le bouton TikTok"
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="show_header_website",
            field=models.BooleanField(
                default=True, verbose_name="Afficher le bouton Site web"
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="show_header_x",
            field=models.BooleanField(
                default=True, verbose_name="Afficher le bouton X / Twitter"
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="show_header_youtube",
            field=models.BooleanField(
                default=True, verbose_name="Afficher le bouton YouTube"
            ),
        ),
    ]
