# Generated by Django 4.2.30 on 2026-08-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0015_split_header_show_toggles"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="contact_align",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Hériter de l'en-tête"),
                    ("left", "Gauche"),
                    ("center", "Centré"),
                    ("right", "Droite"),
                ],
                default="",
                help_text="Vide = hérite de l'alignement de l'en-tête",
                max_length=10,
                verbose_name="Alignement du téléphone / adresse",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="socials_align",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Hériter de l'en-tête"),
                    ("left", "Gauche"),
                    ("center", "Centré"),
                    ("right", "Droite"),
                ],
                default="",
                help_text="Vide = hérite de l'alignement de l'en-tête",
                max_length=10,
                verbose_name="Alignement des boutons réseaux sociaux",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="title_align",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Hériter de l'en-tête"),
                    ("left", "Gauche"),
                    ("center", "Centré"),
                    ("right", "Droite"),
                ],
                default="",
                help_text="Vide = hérite de l'alignement de l'en-tête",
                max_length=10,
                verbose_name="Alignement du nom / titre",
            ),
        ),
    ]
