# Generated by Django 4.2.30 on 2026-09-01 11:45

import app.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0016_add_section_element_aligns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletterimage",
            name="image",
            field=models.ImageField(
                upload_to=app.validators.newsletter_image_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg", "gif", "webp"]
                    ),
                    app.validators.validate_image_content,
                ],
                verbose_name="Image",
            ),
        ),
    ]
