# Generated by Django 4.2.2 on 2026-05-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_tracking', '0004_alter_location_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorcount',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Date'),
        ),
    ]
