# Generated by Django 4.2.2 on 2026-05-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_tracking', '0005_alter_visitorcount_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name="Nom de l'espace"),
        ),
        migrations.AlterField(
            model_name='location',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name="Ordre d'affichage"),
        ),
    ]
