# Generated by Django 4.2.2 on 2026-07-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visitor_tracking", "0006_alter_location_name_alter_location_order"),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS visitor_tracking_weatherdata",
            reverse_sql="",
        ),
    ]
