# Generated by Django 4.2.2 on 2026-07-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitor_tracking", "0006_alter_location_name_alter_location_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "temp_max",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Température max"
                    ),
                ),
                (
                    "temp_min",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Température min"
                    ),
                ),
                (
                    "precipitation",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Précipitations (mm)"
                    ),
                ),
                (
                    "weather_code",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Code météo WMO"
                    ),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Donnée météo",
                "verbose_name_plural": "Données météo",
                "ordering": ["-date"],
            },
        ),
    ]
