# Generated by Django 4.2.30 on 2026-08-28 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LibraryProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="Nom de la médiathèque"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="newsletter/libraries/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        help_text="Image large pour l'en-tête newsletter (ex. 1200×400)",
                        null=True,
                        upload_to="newsletter/banners/",
                        verbose_name="Bannière",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Téléphone"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Adresse"
                    ),
                ),
                (
                    "opening_hours",
                    models.TextField(
                        blank=True,
                        help_text="Une ligne par jour, ex. « Lundi : 14h - 18h »",
                        verbose_name="Horaires d'ouverture",
                    ),
                ),
                (
                    "closures",
                    models.TextField(
                        blank=True,
                        help_text="Une fermeture par ligne",
                        verbose_name="Fermetures exceptionnelles",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, max_length=255, verbose_name="Site web"
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(
                        blank=True, max_length=255, verbose_name="Facebook"
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True, max_length=255, verbose_name="Instagram"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modification"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="library_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Compte médiathèque",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiche médiathèque",
                "verbose_name_plural": "Fiches médiathèques",
            },
        ),
    ]
