# Generated by Django 4.2.30 on 2026-08-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_mediatheque_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="libraryprofile",
            name="tiktok_url",
            field=models.URLField(blank=True, max_length=255, verbose_name="TikTok"),
        ),
        migrations.AddField(
            model_name="libraryprofile",
            name="x_url",
            field=models.URLField(
                blank=True, max_length=255, verbose_name="X / Twitter"
            ),
        ),
        migrations.AddField(
            model_name="libraryprofile",
            name="youtube_url",
            field=models.URLField(blank=True, max_length=255, verbose_name="YouTube"),
        ),
    ]
