# Generated by Django 4.2.30 on 2026-09-01 11:45

import app.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_social_network_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libraryprofile",
            name="banner",
            field=models.ImageField(
                blank=True,
                help_text="Image large pour l'en-tête newsletter (ex. 1200×400)",
                null=True,
                upload_to=app.validators.library_banner_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg", "gif", "webp"]
                    ),
                    app.validators.validate_image_content,
                ],
                verbose_name="Bannière",
            ),
        ),
        migrations.AlterField(
            model_name="libraryprofile",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=app.validators.library_image_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg", "gif", "webp"]
                    ),
                    app.validators.validate_image_content,
                ],
                verbose_name="Logo",
            ),
        ),
    ]
