# Generated by Django 4.2.2 on 2026-05-12 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('zip_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='structure_images')),
                ('valid', models.BooleanField(default=True)),
                ('is_registered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('quantity', models.PositiveIntegerField()),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('reminder_sent', models.BooleanField(default=False, help_text='Indique si le rappel J-1 a été envoyé pour cette réservation', verbose_name='Rappel envoyé')),
                ('deposit_time', models.TimeField(null=True)),
                ('pickup_time', models.TimeField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('disapproval_reason', models.CharField(blank=True, choices=[('error', 'Erreur dans la demande'), ('conflict', 'Réservation en attente soumise avant celle-ci'), ('unavailable', 'Produit non disponible'), ('other', 'Autre raison')], max_length=20, null=True, verbose_name='Raison de désapprobation')),
                ('disapproval_comment', models.TextField(blank=True, null=True, verbose_name='Commentaire de désapprobation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.structure')),
            ],
        ),
    ]
