# Generated by Django 4.2.2 on 2026-05-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_status_alter_reservation_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reminder_sent',
            field=models.BooleanField(db_index=True, default=False, help_text='Indique si le rappel J-1 a été envoyé pour cette réservation', verbose_name='Rappel envoyé'),
        ),
    ]
