# Generated by Django 4.2.2 on 2026-05-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_reservation_reminder_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='disapproval_reason',
            field=models.CharField(blank=True, choices=[('error', 'Erreur dans la demande'), ('conflict', 'Réservation en attente soumise avant celle-ci'), ('unavailable', 'Produit non disponible'), ('other', 'Autre raison')], db_index=True, max_length=20, null=True, verbose_name='Raison de désapprobation'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
