# Generated by Django 4.2.2 on 2026-05-21 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_category_name_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-start_date'], 'verbose_name': 'Réservation', 'verbose_name_plural': 'Réservations'},
        ),
        migrations.AlterModelOptions(
            name='structure',
            options={'ordering': ['name'], 'verbose_name': 'Structure', 'verbose_name_plural': 'Structures'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='shop.structure'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['start_date', 'end_date'], name='idx_reservation_dates'),
        ),
    ]
