# Generated by Django 4.2.2 on 2026-05-22 12:04

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="product_images",
                validators=[app.validators.validate_image_extension],
            ),
        ),
        migrations.AlterField(
            model_name="structure",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="structure_images",
                validators=[app.validators.validate_image_extension],
            ),
        ),
    ]
