# Generated by Django 4.2.2 on 2026-05-21 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(db_index=True)),
                ('date_end', models.DateField(blank=True, db_index=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('poster_required', models.BooleanField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='ateliers_images')),
                ('number_registered', models.IntegerField(blank=True, default=0, null=True)),
                ('number_attendees', models.IntegerField(blank=True, default=0, null=True)),
                ('class_welcome', models.BooleanField(default=False)),
                ('instagram', models.BooleanField(default=False, null=True)),
                ('facebook', models.BooleanField(default=False, null=True)),
                ('mail', models.BooleanField(default=False, null=True)),
                ('portail', models.BooleanField(default=False, null=True)),
                ('vdn', models.BooleanField(default=False, null=True)),
                ('poster_valide', models.BooleanField(default=False, null=True)),
                ('description_poster_valide', models.TextField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.location')),
            ],
        ),
    ]
