# Generated by Django 4.2.2 on 2026-05-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='class_welcome',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='facebook',
            field=models.BooleanField(db_index=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='instagram',
            field=models.BooleanField(db_index=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='mail',
            field=models.BooleanField(db_index=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='portail',
            field=models.BooleanField(db_index=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='poster_required',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='vdn',
            field=models.BooleanField(db_index=True, default=False, null=True),
        ),
    ]
