# Generated by Django 4.2.2 on 2026-05-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_alter_workshop_class_welcome_alter_workshop_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='number_registered',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
    ]
