# Generated by Django 4.2.2 on 2026-05-21 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_alter_location_city_alter_workshop_number_registered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Lieu', 'verbose_name_plural': 'Lieux'},
        ),
        migrations.AlterModelOptions(
            name='workshop',
            options={'ordering': ['-date'], 'verbose_name': 'Atelier', 'verbose_name_plural': 'Ateliers'},
        ),
        migrations.AlterField(
            model_name='workshop',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='workshop.location'),
        ),
    ]
