# Generated by Django 4.2.2 on 2026-05-22 12:04

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0004_alter_location_options_alter_workshop_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshop",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="ateliers_images",
                validators=[app.validators.validate_image_extension],
            ),
        ),
    ]
