# Generated by Django 4.2.30 on 2026-09-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0005_alter_workshop_image"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="workshop",
            index=models.Index(
                fields=["date", "class_welcome"], name="idx_workshop_date_class"
            ),
        ),
        migrations.AddIndex(
            model_name="workshop",
            index=models.Index(
                fields=["location", "date"], name="idx_workshop_loc_date"
            ),
        ),
        migrations.AddIndex(
            model_name="workshop",
            index=models.Index(
                fields=["date", "number_registered"],
                name="idx_workshop_date_registered",
            ),
        ),
    ]
