# Generated by Django 5.1.7 on 2025-08-05 14:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkshopCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom de la catégorie"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#007bff",
                        help_text="Code couleur hexadécimal (ex: #007bff)",
                        max_length=7,
                        verbose_name="Couleur",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="bx-book",
                        help_text="Classe CSS de l'icône (ex: bx-book)",
                        max_length=50,
                        verbose_name="Icône",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie d'atelier",
                "verbose_name_plural": "Catégories d'ateliers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Workshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Ex: Atelier de Lecture pour Enfants",
                        max_length=200,
                        verbose_name="Titre de l'atelier",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description détaillée de l'atelier",
                        verbose_name="Description",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Laissez vide si l'atelier se déroule sur une seule journée",
                        null=True,
                        verbose_name="Date de fin",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Heure de début")),
                ("end_time", models.TimeField(verbose_name="Heure de fin")),
                (
                    "location",
                    models.CharField(
                        help_text="Ex: Salle de lecture principale",
                        max_length=100,
                        verbose_name="Lieu",
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        default=15,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Nombre maximum de participants",
                    ),
                ),
                (
                    "poster",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="workshop_posters/",
                        verbose_name="Affiche de l'atelier",
                    ),
                ),
                (
                    "is_all_ages",
                    models.BooleanField(
                        default=True,
                        help_text="Cochez si l'atelier est ouvert à tous les âges",
                        verbose_name="Tout public",
                    ),
                ),
                (
                    "min_age",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Âge minimum requis (0-100 ans)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Âge minimum",
                    ),
                ),
                (
                    "max_age",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Âge maximum autorisé (0-100 ans)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Âge maximum",
                    ),
                ),
                (
                    "newsletter",
                    models.BooleanField(
                        default=True,
                        help_text="Cochez pour envoyer une newsletter pour cet atelier",
                        verbose_name="Newsletter",
                    ),
                ),
                (
                    "is_class_welcome",
                    models.BooleanField(
                        default=False,
                        help_text="Cochez si cet atelier peut accueillir des classes",
                        verbose_name="Accueil de classe",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_workshops",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atelier",
                "verbose_name_plural": "Ateliers",
                "ordering": ["start_date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="WorkshopParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=50, verbose_name="Nom")),
                (
                    "age",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(120),
                        ],
                        verbose_name="Âge",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Téléphone"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmé"),
                            ("waiting", "Liste d'attente"),
                            ("cancelled", "Annulé"),
                        ],
                        default="confirmed",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "registration_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'inscription"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Informations supplémentaires sur le participant",
                        null=True,
                        verbose_name="Notes",
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_participants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ajouté par",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="library_workshops.workshop",
                        verbose_name="Atelier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participant",
                "verbose_name_plural": "Participants",
                "ordering": ["registration_date"],
                "unique_together": {("workshop", "first_name", "last_name", "email")},
            },
        ),
    ]
