# Generated by Django 5.1.7 on 2025-08-06 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_workshops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshopparticipant",
            name="group_leader",
            field=models.ForeignKey(
                blank=True,
                help_text="Responsable du groupe si ce participant fait partie d'un groupe",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_members",
                to="library_workshops.workshopparticipant",
                verbose_name="Responsable du groupe",
            ),
        ),
        migrations.AddField(
            model_name="workshopparticipant",
            name="group_size",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Nombre total de personnes dans le groupe (incluant le responsable)",
                verbose_name="Taille du groupe",
            ),
        ),
        migrations.AddField(
            model_name="workshopparticipant",
            name="is_group_leader",
            field=models.BooleanField(
                default=False,
                help_text="Cochez si cette personne est responsable d'un groupe",
                verbose_name="Responsable du groupe",
            ),
        ),
    ]
