# Generated by Django 5.1.7 on 2025-08-06 14:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("library_workshops", "0002_workshopparticipant_group_leader_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="workshopparticipant",
            unique_together=set(),
        ),
    ]
