# Generated by Django 5.1.7 on 2025-11-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_workshops", "0003_remove_unique_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshop",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Ex: Salle de lecture principale",
                max_length=100,
                verbose_name="Lieu",
            ),
        ),
    ]
