# Generated by Django 4.2.2 on 2026-05-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_workshops', '0004_alter_workshop_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, help_text="Laissez vide si l'atelier se déroule sur une seule journée", null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='location',
            field=models.CharField(help_text='Ex: Salle de lecture principale', max_length=100, verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='start_date',
            field=models.DateField(db_index=True, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='workshopparticipant',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmé'), ('waiting', "Liste d'attente"), ('cancelled', 'Annulé')], db_index=True, default='confirmed', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['start_date', 'start_time'], name='idx_workshop_start'),
        ),
        migrations.AddIndex(
            model_name='workshopparticipant',
            index=models.Index(fields=['workshop', 'status'], name='idx_participant_ws_status'),
        ),
    ]
