# Generated by Django 4.2.2 on 2026-05-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_workshops', '0006_migrate_location_to_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Indique si le rappel J-1 a été envoyé', verbose_name='Rappel envoyé'),
        ),
    ]
