# Generated by Django 4.2.2 on 2026-05-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_workshops', '0007_workshop_reminder_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='is_class_welcome',
            field=models.BooleanField(db_index=True, default=False, help_text='Cochez si cet atelier peut accueillir des classes', verbose_name='Accueil de classe'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='newsletter',
            field=models.BooleanField(db_index=True, default=True, help_text='Cochez pour envoyer une newsletter pour cet atelier', verbose_name='Newsletter'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='reminder_sent',
            field=models.BooleanField(db_index=True, default=False, help_text='Indique si le rappel J-1 a été envoyé', verbose_name='Rappel envoyé'),
        ),
        migrations.AlterField(
            model_name='workshopparticipant',
            name='is_group_leader',
            field=models.BooleanField(db_index=True, default=False, help_text="Cochez si cette personne est responsable d'un groupe", verbose_name='Responsable du groupe'),
        ),
    ]
