# Generated by Django 4.2.2 on 2026-05-21 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_workshops', '0008_alter_workshop_is_class_welcome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopparticipant',
            name='age',
            field=models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='Âge'),
        ),
        migrations.AlterField(
            model_name='workshopparticipant',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Date d'inscription"),
        ),
    ]
