# Generated by Django 4.2.2 on 2026-05-22 12:04

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_workshops", "0009_alter_workshopparticipant_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshop",
            name="poster",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="workshop_posters/",
                validators=[app.validators.validate_image_extension],
                verbose_name="Affiche de l'atelier",
            ),
        ),
    ]
