# Generated by Django 4.2.2 on 2026-06-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_workshops", "0010_alter_workshop_poster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshop",
            name="title",
            field=models.CharField(
                db_index=True,
                help_text="Ex: Atelier de Lecture pour Enfants",
                max_length=200,
                verbose_name="Titre de l'atelier",
            ),
        ),
    ]
