# Generated by Django 4.2.2 on 2026-06-09 09:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("visitor_tracking", "0006_alter_location_name_alter_location_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("library_workshops", "0011_add_title_db_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "start_date",
                    models.DateField(db_index=True, verbose_name="Date de début"),
                ),
                ("end_date", models.DateField(verbose_name="Date de fin")),
                (
                    "zone",
                    models.CharField(
                        choices=[("A", "Zone A"), ("B", "Zone B"), ("C", "Zone C")],
                        db_index=True,
                        default="B",
                        max_length=1,
                        verbose_name="Zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vacance scolaire",
                "verbose_name_plural": "Vacances scolaires",
                "ordering": ["start_date"],
            },
        ),
        migrations.AddField(
            model_name="workshop",
            name="recurrence_modified",
            field=models.BooleanField(
                default=False,
                help_text="True si cette occurrence a été éditée individuellement",
                verbose_name="Occurrence modifiée",
            ),
        ),
        migrations.CreateModel(
            name="RecurrencePattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        unique=True,
                        verbose_name="Identifiant du groupe",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Toutes les semaines"),
                            ("biweekly", "Toutes les 2 semaines"),
                            ("monthly", "Tous les mois"),
                        ],
                        max_length=20,
                        verbose_name="Fréquence",
                    ),
                ),
                (
                    "interval",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Toutes les X semaines (ignoré pour mensuel)",
                        verbose_name="Intervalle",
                    ),
                ),
                (
                    "days_of_week",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste des index de jours (0=Lundi…5=Samedi)",
                        verbose_name="Jours de la semaine",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Date de début")),
                ("period_end", models.DateField(verbose_name="Date de fin")),
                (
                    "excluded_dates",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste des dates ISO à exclure",
                        verbose_name="Dates exclues",
                    ),
                ),
                (
                    "month_day",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Pour récurrence mensuelle : 15 = le 15 du mois",
                        null=True,
                        verbose_name="Jour du mois",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description")),
                ("start_time", models.TimeField(verbose_name="Heure de début")),
                ("end_time", models.TimeField(verbose_name="Heure de fin")),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        default=15,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Participants max",
                    ),
                ),
                (
                    "is_all_ages",
                    models.BooleanField(default=True, verbose_name="Tout public"),
                ),
                (
                    "min_age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Âge minimum"
                    ),
                ),
                (
                    "max_age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Âge maximum"
                    ),
                ),
                (
                    "newsletter",
                    models.BooleanField(default=True, verbose_name="Newsletter"),
                ),
                (
                    "is_class_welcome",
                    models.BooleanField(
                        default=False, verbose_name="Accueil de classe"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="visitor_tracking.location",
                        verbose_name="Lieu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pattern de récurrence",
                "verbose_name_plural": "Patterns de récurrence",
            },
        ),
        migrations.AddField(
            model_name="workshop",
            name="recurrence_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workshops",
                to="library_workshops.recurrencepattern",
                verbose_name="Groupe de récurrence",
            ),
        ),
    ]
