# Generated by Django 4.2.2 on 2026-06-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "library_workshops",
            "0012_schoolholiday_workshop_recurrence_modified_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurrencepattern",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Tous les jours"),
                    ("every_2_days", "Tous les 2 jours"),
                    ("weekly", "Toutes les semaines"),
                    ("biweekly", "Toutes les 2 semaines"),
                    ("every_3_weeks", "Toutes les 3 semaines"),
                    ("monthly", "Tous les mois"),
                    ("every_2_months", "Tous les 2 mois"),
                ],
                max_length=20,
                verbose_name="Fréquence",
            ),
        ),
    ]
