# Generated by Django 4.2.2 on 2026-06-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_workshops", "0013_alter_recurrencepattern_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="cancellation_reason",
            field=models.TextField(
                blank=True,
                help_text="Raison de l'annulation de l'atelier",
                null=True,
                verbose_name="Motif d'annulation",
            ),
        ),
        migrations.AddField(
            model_name="workshop",
            name="status",
            field=models.CharField(
                choices=[("active", "Actif"), ("cancelled", "Annulé")],
                db_index=True,
                default="active",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
