# Generated by Django 4.2.2 on 2026-06-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_workshops", "0014_workshop_cancellation_reason_workshop_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurrencepattern",
            name="poster",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="workshop_posters/",
                verbose_name="Affiche",
            ),
        ),
    ]
