# Generated by Django 4.2.30 on 2026-08-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_workshops", "0015_recurrencepattern_poster"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="workshop",
            index=models.Index(
                fields=["newsletter", "status", "start_date"],
                name="idx_ws_news_stat_date",
            ),
        ),
    ]
