# Generated by Django 4.2.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Adresse email du destinataire', max_length=254, unique=True, verbose_name='Adresse email')),
                ('is_active', models.BooleanField(default=True, help_text='Désactiver pour ne plus recevoir de notifications', verbose_name='Actif')),
                ('notification_type', models.CharField(choices=[('reservation_reminder', 'Rappel de réservation')], default='reservation_reminder', help_text='Type de notification à recevoir', max_length=50, verbose_name='Type de notification')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Destinataire de notification',
                'verbose_name_plural': 'Destinataires de notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('recipients', models.TextField(help_text='Liste des adresses email ayant reçu le rappel', verbose_name='Destinataires')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='shop.reservation', verbose_name='Réservation')),
            ],
            options={
                'verbose_name': 'Rappel de réservation',
                'verbose_name_plural': 'Rappels de réservations',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notificationrecipient',
            index=models.Index(fields=['is_active', 'notification_type'], name='notificatio_is_acti_idx'),
        ),
        migrations.AddIndex(
            model_name='reservationreminder',
            index=models.Index(fields=['reservation', 'sent_at'], name='notificatio_reserva_idx'),
        ),
    ]
