# Generated by Django 4.2.2

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_send_hour', models.IntegerField(default=9, help_text='Heure d\'envoi des rappels (0-23). Par défaut : 9h00', validators=[MinValueValidator(0), MaxValueValidator(23)], verbose_name="Heure d'envoi")),
                ('reminder_send_minute', models.IntegerField(default=0, help_text='Minute d\'envoi des rappels (0-59). Par défaut : 0', validators=[MinValueValidator(0), MaxValueValidator(59)], verbose_name='Minute d\'envoi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Paramètres de notification',
                'verbose_name_plural': 'Paramètres de notification',
                'ordering': ['-updated_at'],
            },
        ),
    ]





