# Generated by Django 4.2.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='reminders_enabled',
            field=models.BooleanField(default=True, help_text="Active ou désactive l'envoi automatique des rappels de réservation. Activé par défaut.", verbose_name='Rappels activés'),
        ),
    ]





