# Generated by Django 4.2.2 on 2026-05-15 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_workshops', '0007_workshop_reminder_sent'),
        ('notifications', '0003_notificationsettings_reminders_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('recipients', models.TextField(help_text='Liste des adresses email ayant reçu le rappel', verbose_name='Destinataires')),
            ],
            options={
                'verbose_name': "Rappel d'atelier",
                'verbose_name_plural': "Rappels d'ateliers",
                'ordering': ['-sent_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='notificationrecipient',
            new_name='notificatio_is_acti_4f182c_idx',
            old_name='notificatio_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='reservationreminder',
            new_name='notificatio_reserva_6db6da_idx',
            old_name='notificatio_reserva_idx',
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='workshop_reminders_enabled',
            field=models.BooleanField(default=True, help_text="Active ou désactive l'envoi automatique des rappels d'atelier.", verbose_name='Rappels atelier activés'),
        ),
        migrations.AlterField(
            model_name='notificationrecipient',
            name='notification_type',
            field=models.CharField(choices=[('reservation_reminder', 'Rappel de réservation'), ('workshop_reminder', "Rappel d'atelier")], default='reservation_reminder', help_text='Type de notification à recevoir', max_length=50, verbose_name='Type de notification'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='reminders_enabled',
            field=models.BooleanField(default=True, help_text="Active ou désactive l'envoi automatique des rappels de réservation.", verbose_name='Rappels réservation activés'),
        ),
        migrations.AddField(
            model_name='workshopreminder',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='library_workshops.workshop', verbose_name='Atelier'),
        ),
        migrations.AddIndex(
            model_name='workshopreminder',
            index=models.Index(fields=['workshop', 'sent_at'], name='notificatio_worksho_6be558_idx'),
        ),
    ]
