# Generated by Django 4.2.2 on 2026-05-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_workshopreminder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrecipient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
    ]
