# Generated by Django 4.2.2 on 2026-05-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_alter_notificationrecipient_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("new_reservation", "Nouvelle réservation"),
                            ("reservation_approved", "Réservation approuvée"),
                            ("reservation_disapproved", "Réservation désapprouvée"),
                            ("structure_validated", "Structure validée"),
                            ("poster_request", "Demande d'affiche"),
                            ("poster_validated", "Affiche validée"),
                            ("poster_rejected", "Affiche rejetée"),
                            ("poster_image_uploaded", "Image d'affiche ajoutée"),
                            ("reservation_reminder", "Rappel de réservation"),
                            ("workshop_reminder", "Rappel d'atelier"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Type de notification",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Sujet de l'email. Utilisez {{ variable }} pour les données dynamiques.",
                        max_length=255,
                        verbose_name="Sujet de l'email",
                    ),
                ),
                (
                    "body_html",
                    models.TextField(
                        help_text="Template HTML complet. Variables disponibles selon le contexte.",
                        verbose_name="Corps HTML",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Désactiver pour ne pas envoyer ce type de notification.",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Template d'email",
                "verbose_name_plural": "Templates d'emails",
                "ordering": ["notification_type"],
            },
        ),
        migrations.AlterField(
            model_name="notificationrecipient",
            name="email",
            field=models.EmailField(
                help_text="Adresse email du destinataire",
                max_length=254,
                verbose_name="Adresse email",
            ),
        ),
        migrations.AlterField(
            model_name="notificationrecipient",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("new_reservation", "Nouvelle réservation"),
                    ("reservation_approved", "Réservation approuvée"),
                    ("reservation_disapproved", "Réservation désapprouvée"),
                    ("structure_validated", "Structure validée"),
                    ("poster_request", "Demande d'affiche"),
                    ("poster_validated", "Affiche validée"),
                    ("poster_rejected", "Affiche rejetée"),
                    ("poster_image_uploaded", "Image d'affiche ajoutée"),
                    ("reservation_reminder", "Rappel de réservation"),
                    ("workshop_reminder", "Rappel d'atelier"),
                ],
                default="reservation_reminder",
                help_text="Type de notification à recevoir",
                max_length=50,
                verbose_name="Type de notification",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notificationrecipient",
            unique_together={("email", "notification_type")},
        ),
    ]
